version: '1'
services:
  frontend:
    image: frontend:latest  
    ports:
      - "80:3000"  # Map port 80 on the host to port 3000 in the container
    environment:
      - REACT_APP_API_URL=http://backend:4000  # Set the API URL for your frontend. This is from nodejs!

  backend:
    image: backend:latest  
    ports:
      - "4000:4000"  # Map port 4000 on the host to port 4000 in the container
    depends_on:
      - database  # Ensure the database service starts before the backend
    environment:
      - DATABASE_URL=sqlite:///database.sqlite   # the database URL

  database:
    image: "sqlite:latest"
    volumes:
      - ./data:/data  # Mount a volume to persist the SQLite database file
    command: ["/bin/sh", "-c", "cp /var/lib/sqlite/data/database.sqlite /data/database.sqlite"]

